### ISSUE TITLE
Handle GRPC connections

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/api-gateway#187]
Currently, When a healthcheck fails for a service, API-Gateway fails as well. 
This happens because it doesn't have an option of re-connecting to a lost connection. 

DOD: 
 - api-gateway handles connections gracefully and only fails for fatal services, such as: file-service, download, upload.
 - code works, passes CR and was tested properly.

**Comment by nogahaskal** [comment]
closed in #107
