### ISSUE TITLE
Upload Route

### ISSUE THREAD

**Issue by omrishtam** [meateam/api-gateway#2]
`POST /upload?uploadType=<type>`
## There are 3 types of uploads:

1. Simple upload: uploadType=media. For quick transfer of a small file (5 MB or less). To perform a simple upload, refer to Perform a Simple Upload.
Perform a simple upload
A simple upload is the most straightforward method for uploading a file. Use this option if:

- The file is small enough to upload again in its entirety if the connection fails.
- There is no metadata to send. This might be true if you plan to send metadata for the file in a separate request, or if no metadata is available.
- If you need to provide metadata for the file, you can use multipart upload or resumable upload instead. For larger files (more than 5 MB) or less reliable network connections, use resumable upload.

2. Multipart upload: uploadType=multipart. For quick transfer of a small file (5 MB or less) and metadata describing the file, all in a single request. To perform a multipart upload.
- A multipart upload request allows you to send metadata along with the data to upload. Use this option if the data you are sending is small enough to upload again in its entirety if the connection fails. If your file does not have any metadata, use simple upload instead. For larger files (more than 5 MB) or less reliable network connections, use resumable upload instead.

3. Resumable upload: uploadType=resumable. For more reliable transfer, especially important with large files. Resumable uploads are a good choice for most applications, since they also work for small files at the cost of one additional HTTP request per upload. To perform a resumable upload, perform a Resumable Upload.
This protocol allows you to resume an upload operation after a communication failure interrupts the flow of data. Use this option if:

- You are transferring large files.
- The likelihood of a network interruption or some other transmission failure is high (for example, if you are uploading a file from a mobile app).
- Resumable uploads can also reduce your bandwidth usage when there is a network failure, because you don't have to restart large file uploads from the beginning.
- If you are sending small files over a reliable network connection, you can use simple upload or multipart upload instead.

### **Checklist - Without file service**
- [X] media upload
- [x] multipart upload
- [x] resumable upload

### **Checklist - With file service**
- [x] media upload
- [x] multipart upload
- [x] resumable upload

**Comment by omerzamir** [comment]
[feature/upload](/meateam/api-gateway/tree/feature/upload)

**Comment by omrishtam** [comment]
Need to add per-part error handling when streaming the uploaded file's parts to the upload-service, after that and some tests that it works we can say it's done.

**Comment by omrishtam** [comment]
Done in #22
