### ISSUE TITLE
Download Route

### ISSUE THREAD

**Issue by omrishtam** [meateam/api-gateway#3]
Using `GET /files/<fileid>?alt=media`
To download files, you make an authorized HTTP GET request to the file's resource URL and include the query parameter alt=media. For example:

`GET /files/0B9jNhSvVjoIVM3dKcGRKRmVIOVU?alt=media`
Authorization: Bearer <ACCESS_TOKEN>
File downloads initiated from your app require at least read access. Users with edit permission may restrict downloading by read-only users by setting the viewersCanCopyContent field to true.

**Comment by omerzamir** [comment]
- [X] implemented without file service
- [ ] implemented with file service

**Comment by omrishtam** [comment]
Route is `GET /download/<fileId>` so we need to merge it with #4 to be under `GET /files/<fileId>`, after that it's done.

**Comment by omrishtam** [comment]
Done in #21
