### ISSUE TITLE
Implement API functionality for retrieving folder's ancestors

### ISSUE THREAD

**Issue by avivbarel** [meateam/api-gateway#99]
Do this one right after the issue in file-service

- [x] done in file-service
- [x] done in api-gateway

**Comment by AllKinds** [comment]
After this issue is closed we need to consider taking care of [authentication-service #29](https://github.com/meateam/authentication-service/issues/29).
We will also have to decide what to do if the user is not the owner of the folder (it should return the route to the highest shared ancestor).
